"""add image_url and is_veg to menu items

Revision ID: 0beb636ba110
Revises: 1f02643dacd6
Create Date: 2026-06-15 09:47:12.232039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0beb636ba110'
down_revision = '1f02643dacd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_veg', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('is_veg')

    # ### end Alembic commands ###
