"""empty message

Revision ID: 1f02643dacd6
Revises: 37a1d3d6824e
Create Date: 2026-05-20 20:00:44.623943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1f02643dacd6'
down_revision = '37a1d3d6824e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafe_tables')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('table_no',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('customer_session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_session_id', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.alter_column('table_no',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('cafe_tables',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('table_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=64, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('qr_path', sa.VARCHAR(length=512, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('qr_code', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('qr_generated_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__cafe_tab__3213E83FD5E1F64C'))
    )
    # ### end Alembic commands ###
