"""schema check

Revision ID: a5bda0750587
Revises: ca94401716d6
Create Date: 2026-06-17 11:17:22.731135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bda0750587'
down_revision = 'ca94401716d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=False),
    sa.Column('qr_url', sa.Text(), nullable=False),
    sa.Column('qr_image_base64', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_codes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_codes_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_codes_table_no'), ['table_no'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_codes_table_no'))
        batch_op.drop_index(batch_op.f('ix_qr_codes_is_active'))
        batch_op.drop_index(batch_op.f('ix_qr_codes_created_at'))

    op.drop_table('qr_codes')
    # ### end Alembic commands ###
