"""add payment_settings table

Revision ID: ca94401716d6
Revises: d8453575c2af
Create Date: 2026-06-17 10:18:08.337629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'ca94401716d6'
down_revision = 'd8453575c2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upi_id', sa.String(length=256), nullable=True),
    sa.Column('account_name', sa.String(length=256), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('qr_image_base64', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_codes_created_at'))
        batch_op.drop_index(batch_op.f('ix_qr_codes_is_active'))
        batch_op.drop_index(batch_op.f('ix_qr_codes_table_no'))

    op.drop_table('qr_codes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('table_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_url', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('qr_image_base64', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('is_active', mssql.BIT(), server_default=sa.text("('1')"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__qr_codes__3213E83F013B74BA'))
    )
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_codes_table_no'), ['table_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_codes_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_codes_created_at'), ['created_at'], unique=False)

    op.drop_table('payment_settings')
    # ### end Alembic commands ###
