"""add payment fields to order

Revision ID: d8453575c2af
Revises: e6676dc7fa1f
Create Date: 2026-06-15 23:15:48.350269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8453575c2af'
down_revision = 'e6676dc7fa1f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'payment_status',
            sa.String(length=20),
            nullable=False,
            server_default='unpaid'
        ))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('paid_at')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
