"""Add is_active to menu_items

Revision ID: db15d3fcf4e0
Revises: ef454f5c8a0b
Create Date: 2026-01-24 19:57:22.870336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db15d3fcf4e0'
down_revision = 'ef454f5c8a0b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("menu_items") as batch_op:
        batch_op.add_column(
            sa.Column("is_active", sa.Boolean(), nullable=True, server_default=sa.text("1"))
        )

    op.execute("UPDATE menu_items SET is_active = 1 WHERE is_active IS NULL")

    with op.batch_alter_table("menu_items") as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.Boolean(),
            nullable=False
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
