"""Add customer_session_id to orders

Revision ID: fc940439d477
Revises: f3ab1198c9ee
Create Date: 2026-07-02 22:09:52.919347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc940439d477'
down_revision = 'f3ab1198c9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_session_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_customer_session_id'), ['customer_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_customer_session_id'))
        batch_op.drop_column('customer_session_id')

    # ### end Alembic commands ###
